<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <AssemblyName>DockyDock</AssemblyName>
    <RootNamespace>DockyDock</RootNamespace>
    <NoWarn>$(NoWarn);WFO0003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icons\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
